test = {   'name': 'q1_5',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(by_content, bpd.DataFrame)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> by_content.shape[0] == 6\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> by_content.get(by_content.columns[0]).index[0] == 'Adults only 18+'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> by_content.get(by_content.columns[0]).iloc[0] == 3 # There are 3 apps with Content Rating 'Adults only 18+'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
