test = {   'name': 'q3_2_1',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> seconds_in_an_hour != 3600 # Oops! The number of seconds in an hour is not quite that. It is somewhere between 3599 and 3601.\nFalse',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> seconds_in_an_hour == 3600\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
