test = {   'name': 'q3_3',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> np.mean(left_end) > 90\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.mean(left_end) < 100\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.mean(right_end) > 145\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.mean(right_end) < 155\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
