test = {   'name': 'q3_5',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> 0 < simulating_q5 < 6\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> simulating_q5 != 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> simulating_q5 != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> simulating_q5 != 4\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> simulating_q5 != 5\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
