test = {   'name': 'q5_5',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> new_predict in [1, 2, 3, 4]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> new_predict != 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> new_predict != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> new_predict != 3\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
