test = {   'name': 'q1_3',
    'points': None,
    'suites': [   {   'cases': [   {   'code': ">>> callable(ci_and_hist) and (Ljubljana_string != None) # Make sure your function returns a string, and doesn't just print one\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> Ljubljana_string[:65] == 'A 99% confidence interval for average hotel price of Ljubljana is'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
